version = 0.1

[default]
[default.global.parameters]
stack_name = "winking-owl-audits-api-dev"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
resolve_s3 = true
s3_prefix = "winking-owl-audits-api"
parameter_overrides = [
    "Stage=dev",
    "CognitoUserPoolId=YOUR_COGNITO_USER_POOL_ID"
]

[default.package.parameters]
resolve_s3 = true

[production]
[production.global.parameters]
stack_name = "winking-owl-audits-api-prod"

[production.build.parameters]
cached = true
parallel = true

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
resolve_s3 = true
s3_prefix = "winking-owl-audits-api"
parameter_overrides = [
    "Stage=prod",
    "CognitoUserPoolId=YOUR_COGNITO_USER_POOL_ID"
]
